### PR TITLE
Cu 862jff3zj adding deleted flag piotr kryszkiewicz

### PR DESCRIPTION
**Pull request by Kryhowsky**

### CODE REVIEW

**Comment by ksidor93** [comment]
Task linked: [CU-862jff3zj Adding deleted flag](https://app.clickup.com/t/862jff3zj)

**Review by s21670-Pyrzak-Tomasz-gr-18C — APPROVED** [review]
Poddałem się w połowie :-)

**Comment by kurylek** [comment]
Potrzebne są jeszcze drobne poprawki- ogarniemy to!

**Review by kurylek — CHANGES_REQUESTED** [review]
Looks fine, but I have to add filtering by deleted and adding deleted flag for childs

**Review by kurylek — APPROVED** [review]
Should work fine, we'll see..

**Pull request merged**
