### PR TITLE
Added handling of EntityNotFoundExceptions, fixed bug with POST for E…

### PR DESCRIPTION
**Pull request by Kryhowsky**
…mployees

Should fix [this](https://app.clickup.com/t/862jb8gr7) and [this](https://app.clickup.com/t/862jb8kkr)

### CODE REVIEW

**Comment by s20146** [comment]
Task linked: [CU-862jb8gr7 Błąd endpointu POST fitters 500](https://app.clickup.com/t/862jb8gr7)

**Comment by s20146** [comment]
Task linked: [CU-862jb8kkr Błąd endpointu DELETE fitters/{id} 500](https://app.clickup.com/t/862jb8kkr)

**Review by kurylek — CHANGES_REQUESTED** [review]
Still can't delete fitter by id

**Comment by Kryhowsky** [comment]
@kurylek More details needed to reproduce failing case or some error stack trace to understand. 
It works for me (😃) when I post new Fitter and use Id of that one to delete.

**Comment by Kryhowsky** [comment]
Probably spot the problem. @kurylek did you mean to remove any Fitter with any association created?
If not, keep me updated with the problem, if so read below.

That's not a problem of Fitter class. It will happen in all Entities whenever you create relationship between them and try to remove them afterwards.
@s21670-Pyrzak-Tomasz-gr-18C and whole backend team we need to make decision about strategy in removing entities. 
I found [this article](https://www.baeldung.com/jpa-cascade-remove-vs-orphanremoval) that can be helpful.

`@OneToMany(cascade = CascadeType.REMOVE, orphanRemoval = true, mappedBy = "updatedBy")`

**Comment by kurylek** [comment]
Yeah, I tried to remove fitter with association...
So it works fine!

**Review by kurylek — APPROVED** [review]

**Pull request merged**
